# Plugin description file
name: cLib
description: Improved bukkit plugin library for Bukkit servers

version: ${pom.version}-b${BUILD_NUMBER}
authors: [SpaceEmotion, p000ison]

main: net.catharos.lib.cLib2
